apiVersion: v1
kind: Pod
metadata:
  name: pod-starrocks-2-5-4-dst
  namespace: dts 
  labels:
    app: starrocks
    version: "2.5.4"
    use: dst
spec:
  containers:
  - name: starrocks-container
    image: starrocks.docker.scarf.sh/starrocks/allin1-ubuntu:2.5.4
    ports:
      - containerPort: 9030
      - containerPort: 8030
      - containerPort: 8040
