apiVersion: v1
kind: Pod
metadata:
  name: pod-starrocks-3-1-5-dst
  namespace: dts 
  labels:
    app: starrocks
    version: "3.1.5"
    use: dst
spec:
  containers:
  - name: starrocks-container
    image: starrocks.docker.scarf.sh/starrocks/allin1-ubuntu:3.1.5
    ports:
      - containerPort: 9030
      - containerPort: 8030
      - containerPort: 8040
