apiVersion: v1
kind: Service
metadata:
  name: service-starrocks-3-1-5-dst
  namespace: dts 
spec:
  selector:
    app: starrocks
    version: "3.1.5"
    use: dst
  ports:
    - protocol: TCP
      port: 9030
      targetPort: 9030
      name: mysql-port
    - protocol: TCP
      port: 8030
      targetPort: 8030
      name: fe-port
    - protocol: TCP
      port: 8040
      targetPort: 8040
      name: be-port
  type: LoadBalancer