apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-rebloom-src
  namespace: dts 
  labels:
    app: redis
    version: "rebloom"
    use: src
spec:
  containers:
  - name: pod-redis-rebloom-src
    image: redislabs/rebloom:2.6.3
    lifecycle:
      postStart:
        exec:
          command: [ "/bin/sh", "-c", "redis-cli config set requirepass 123456" ]
    ports:
    - containerPort: 6379
      protocol: TCP 