apiVersion: v1
kind: Service
metadata:
  name: service-redis-rebloom-src
  namespace: dts 
spec:
  selector:
    app: redis
    version: "rebloom"
    use: src
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer