apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-2-8-dst
  namespace: dts 
  labels:
    app: redis
    version: "2-8"
    use: dst
spec:
  containers:
  - name: pod-redis-2-8-dst
    image: redis:2.8.22
    ports:
    - containerPort: 6379
      protocol: TCP 
    command: ["redis-server"]