apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-2-8-src
  namespace: dts 
  labels:
    app: redis
    version: "2-8"
    use: src
spec:
  containers:
  - name: pod-redis-2-8-src
    image: redis:2.8.22
    lifecycle:
      postStart:
        exec:
          command: [ "/bin/sh", "-c", "redis-cli config set requirepass 123456" ]
    ports:
    - containerPort: 6379
      protocol: TCP 
    command: ["redis-server"]