apiVersion: v1
kind: Service
metadata:
  name: service-redis-rejson-dst
  namespace: dts 
spec:
  selector:
    app: redis
    version: "rejson"
    use: dst
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer