apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-5-0-src
  namespace: dts 
  labels:
    app: redis
    version: "5-0"
    use: src
spec:
  containers:
  - name: pod-redis-5-0-src
    image: redis:5.0
    ports:
    - containerPort: 6379
      protocol: TCP 
    command: ["redis-server"]