apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-5-0-dst
  namespace: dts 
  labels:
    app: redis
    version: "5-0"
    use: dst
spec:
  containers:
  - name: pod-redis-5-0-dst
    image: redis:5.0
    lifecycle:
      postStart:
        exec:
          command: [ "/bin/sh", "-c", "redis-cli config set requirepass 123456" ]
    ports:
    - containerPort: 6379
      protocol: TCP 
    command: ["redis-server"]