name: Rust Cross Build

on:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: main

jobs:
  build:
    name: Cross build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build for x86_64-unknown-linux-musl
        run: cross build --target x86_64-unknown-linux-musl --release

      - name: Build for aarch64-unknown-linux-musl
        run: cross build --target aarch64-unknown-linux-musl --release

      - name: Upload x86_64 binaries
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-binaries
          path: target/x86_64-unknown-linux-musl/release/*

      - name: Upload aarch64 binaries
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-binaries
          path: target/aarch64-unknown-linux-musl/release/*