name: Rust Cross Build

on:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        type: string
        default: main

jobs:
  build:
    name: Cross build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Add build targets
        run: rustup target add aarch64-unknown-linux-musl x86_64-unknown-linux-musl

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install cross
        run: cargo install cross

      - name: Build for x86_64-unknown-linux-musl
        run: cross build --target x86_64-unknown-linux-musl --release

      - name: Build for aarch64-unknown-linux-musl
        run: cross build --target aarch64-unknown-linux-musl --release
